// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwipnefffbgximkidgry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3aXBuZWZmZmJneGlta2lkZ3J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNjc4OTIsImV4cCI6MjA2Nzc0Mzg5Mn0.WaboCk5KjTAV_4UX8uTBHA8Yzz5iemXwGZA89BEiy4A";
// guduruprabhakar0
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});